name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js for frontend
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Set up Java for backend
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install backend dependencies
        run: |
          cd backend
          mvn install -DskipTests

      - name: Start backend server
        run: |
            cd backend
            mvn spring-boot:run -Dspring.profiles.active=test &
            sleep 15

      - name: Run backend tests
        run: |
          cd backend
          mvn test 

      - name: Build frontend application
        run: |
          cd frontend
          npm run build

      - name: Install Cypress
        run: |
          cd frontend
          npm install cypress --save-dev

      - name: Start frontend server
        run: |
          cd frontend
          npm start &

      - name: Run Cypress components tests
        run: |
          cd frontend
          npx cypress run --component

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build       
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository for deployment
        uses: actions/checkout@v2

      - name: Set up Node.js for deployment
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies for deployment
        run: |
          cd frontend
          npm install

      - name: Configure git user info for deployment
        run : |
          git config --global user.email "philip.norrmyr@gmail.com"
          git config --global user.name "PNorrmyr"

      - name: Setup GitHub Authentication for deployment 
        run: |
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Deploy to Github Pages 
        run: |
          cd frontend
          npm run deploy

          
