name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js for frontend
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Set up Java for backend
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install backend dependencies
        run: |
          cd backend
          mvn install -DskipTests  # Skip tests during install to speed up the process

      - name: Start backend server
        run: |
          cd backend
          mvn spring-boot:run

      - name: Run backend tests
        run: |
          cd backend
          mvn test  # Execute tests in the backend

      - name: Build frontend application
        run: |
          cd frontend
          npm run build  # Build the React app

      - name: Install Cypress
        run: |
          cd frontend
          npm install cypress --save-dev

      - name: Start frontend server
        run: |
          cd frontend
          npm start &

      - name: Run Cypress components tests
        run: |
          cd frontend
          npx cypress run --component

